/**
 * Pure functions to generate C/C++ code from project state.
 */

import { getInterpolatedPosition } from './tweenUtils';

// Helper to convert pixels to 1-bit byte array (MSB first, row-major)
const encodeBitmap = (pixels, width, height) => {
  const bytes = [];
  for (let i = 0; i < pixels.length; i += 8) {
    let byte = 0;
    for (let bit = 0; bit < 8; bit++) {
      if (pixels[i + bit]) {
        byte |= (1 << (7 - bit));
      }
    }
    bytes.push(byte);
  }
  return bytes;
};

const sanitizeName = (name) => name.toUpperCase().replace(/[^A-Z0-9]/g, '_');

export const generateCLibrary = (project) => {
  const { meta, sprites, keyframes } = project;
  const name = sanitizeName(meta.name);
  
  let header = `/**\n * MOCHI ANIMATION: ${meta.name}\n * Generated by Mochi Animator v1.0\n */\n\n#pragma once\n#include <stdint.h>\n#include <avr/pgmspace.h>\n\n`;
  let source = `#include "${meta.name}.h"\n\n`;

  const bitmaps = new Map(); // Map of JSON.stringify(pixels) -> { name, bytes }
  let totalProgmem = 0;

  // 1. Bitmaps Deduplication & Generation
  sprites.forEach((sprite, sIdx) => {
    const pixelKey = JSON.stringify(sprite.pixels);
    if (!bitmaps.has(pixelKey)) {
      const bmpName = `MOCHI_BMP_${sanitizeName(sprite.name)}_${sIdx}`;
      const bytes = encodeBitmap(sprite.pixels, sprite.width, sprite.height);
      bitmaps.set(pixelKey, { name: bmpName, bytes });
      totalProgmem += bytes.length;

      header += `// Sprite: ${sprite.name} (${sprite.width}x${sprite.height})\n`;
      header += `static const uint8_t PROGMEM ${bmpName}[] = { ${bytes.map(b => '0x' + b.toString(16).padStart(2, '0')).join(', ')} };\n\n`;
    }
  });

  header += `// Total PROGMEM for bitmaps: ~${totalProgmem} bytes\n\n`;

  // 2. Struct Definitions
  header += `typedef struct {\n  uint8_t x, y, w, h;\n  const uint8_t* bmp;\n} MochiSprite;\n\n`;
  header += `typedef struct {\n  uint8_t frame_count;\n  uint16_t delay_ms;\n  const MochiSprite* frames;\n} MochiLayer;\n\n`;
  header += `typedef struct {\n  uint8_t layer_count;\n  const MochiLayer* layers;\n} MochiAnim;\n\n`;

  // 3. Animation Layers
  sprites.forEach(sprite => {
    const layerVarName = `MOCHI_LAYER_${sanitizeName(sprite.name)}`;
    header += `extern const MochiSprite ${layerVarName}[];\n`;
    
    source += `const MochiSprite ${layerVarName}[] = {\n`;
    for (let f = 0; f < meta.totalFrames; f++) {
      const pos = getInterpolatedPosition(keyframes[sprite.id], f);
      const bmpInfo = bitmaps.get(JSON.stringify(sprite.pixels));
      
      source += `  { .x=${pos.x}, .y=${pos.y}, .w=${sprite.width}, .h=${sprite.height}, .bmp=${bmpInfo.name} }, // frame ${f}\n`;
    }
    source += `};\n\n`;
  });

  // 4. Final Animation Struct
  const layersVarName = `MOCHI_LAYERS_${name}`;
  source += `const MochiLayer ${layersVarName}[] = {\n`;
  sprites.forEach(sprite => {
    const layerVarName = `MOCHI_LAYER_${sanitizeName(sprite.name)}`;
    source += `  { .frame_count=${meta.totalFrames}, .delay_ms=${Math.round(1000/meta.fps)}, .frames=${layerVarName} },\n`;
  });
  source += `};\n\n`;

  source += `const MochiAnim MOCHI_ANIM_${name} = {\n  .layer_count = ${sprites.length},\n  .layers = ${layersVarName}\n};\n`;
  header += `extern const MochiAnim MOCHI_ANIM_${name};\n`;

  return { header, source, memoryUsage: totalProgmem };
};
