/**
 * Pure functions to generate C/C++ code from project state.
 */

import { getInterpolatedPosition } from './tweenUtils';

// Helper to convert pixels to 1-bit byte array (MSB first, row-major)
const encodeBitmap = (pixels, width, height) => {
  const bytes = [];
  for (let i = 0; i < pixels.length; i += 8) {
    let byte = 0;
    for (let bit = 0; bit < 8; bit++) {
      if (pixels[i + bit]) {
        byte |= (1 << (7 - bit));
      }
    }
    bytes.push(byte);
  }
  return bytes;
};

const sanitizeName = (name) => name.toUpperCase().replace(/[^A-Z0-9]/g, '_');

const generateReadme = (project) => {
  const { meta, sprites } = project;
  const name = sanitizeName(meta.name);

  return `# 🤖 Mochi Animation: ${meta.name}
Generated by Mochi Animator

## 📁 File Structure
- \`${meta.name}.h\`: Header file containing bitmap arrays and struct definitions.
- \`${meta.name}.cpp\`: Source file containing animation data and layers.

## 🚀 Quick Start (Arduino/ESP32)

1. Add both files to your Arduino sketch folder.
2. Include the header in your main file:
   \`\`\`cpp
   #include "${meta.name}.h"
   \`\`\`
3. Use the animation struct in your loop:
   \`\`\`cpp
   // Example for U8g2 library
   void drawMochi() {
     const MochiAnim* anim = &MOCHI_ANIM_${name};
     for (int i = 0; i < anim->layer_count; i++) {
       const MochiLayer* layer = &anim->layers[i];
       const MochiSprite* frame = &layer->frames[currentFrame % layer->frame_count];
       u8g2.drawXBMP(frame->x, frame->y, frame->w, frame->h, frame->bmp);
     }
   }
   \`\`\`

## 🎭 Animation Details
- **Total Layers:** ${sprites.length}
- **FPS:** ${meta.fps} (${Math.round(1000/meta.fps)}ms per frame)
- **Resolution:** ${meta.canvasW}x${meta.canvasH}

### Layer List:
${sprites.map(s => `- **${s.name}**: ${s.uiComponents?.length > 0 ? 'UI Component' : 'Pixel Sprite'}`).join('\n')}

---
*Created with Mochi Animator - The Expressive Robot Engine*
`;
};

export const generateCLibrary = (project) => {
  const { meta, sprites, keyframes } = project;
  const name = sanitizeName(meta.name);
  
  let header = `/**\n * MOCHI ANIMATION: ${meta.name}\n * Generated by Mochi Animator v1.0\n */\n\n#pragma once\n#include <stdint.h>\n#include <avr/pgmspace.h>\n\n`;
  let source = `#include "${meta.name}.h"\n\n`;

  const bitmaps = new Map(); // Map of JSON.stringify(pixels) -> { name, bytes }
  let totalProgmem = 0;

  // 1. Bitmaps Deduplication & Generation
  let bmpCounter = 0;
  sprites.forEach((sprite) => {
    for (let f = 0; f < meta.totalFrames; f++) {
      const pos = getInterpolatedPosition(keyframes[sprite.id], f);
      const currentPixels = (!sprite.shapeLocked && pos.pixels) ? pos.pixels : sprite.pixels;
      const pixelKey = JSON.stringify(currentPixels);
      
      if (!bitmaps.has(pixelKey)) {
        const bmpName = `MOCHI_BMP_${sanitizeName(sprite.name)}_${bmpCounter++}`;
        const bytes = encodeBitmap(currentPixels, sprite.width, sprite.height);
        bitmaps.set(pixelKey, { name: bmpName, bytes });
        totalProgmem += bytes.length;

        header += `// Sprite: ${sprite.name} (Frame/Variant ${bmpCounter}) (${sprite.width}x${sprite.height})\n`;
        header += `static const uint8_t PROGMEM ${bmpName}[] = { ${bytes.map(b => '0x' + b.toString(16).padStart(2, '0')).join(', ')} };\n\n`;
      }
    }
  });

  header += `// Total PROGMEM for bitmaps: ~${totalProgmem} bytes\n\n`;

  // 2. Struct Definitions
  header += `typedef struct {\n  uint8_t x, y, w, h;\n  const uint8_t* bmp;\n} MochiSprite;\n\n`;
  header += `typedef struct {\n  uint8_t frame_count;\n  uint16_t delay_ms;\n  const MochiSprite* frames;\n} MochiLayer;\n\n`;
  header += `typedef struct {\n  uint8_t layer_count;\n  const MochiLayer* layers;\n} MochiAnim;\n\n`;

  // 3. Animation Layers
  sprites.forEach(sprite => {
    const layerVarName = `MOCHI_LAYER_${sanitizeName(sprite.name)}`;
    header += `extern const MochiSprite ${layerVarName}[];\n`;
    
    source += `const MochiSprite ${layerVarName}[] = {\n`;
    for (let f = 0; f < meta.totalFrames; f++) {
      const pos = getInterpolatedPosition(keyframes[sprite.id], f);
      const currentPixels = (!sprite.shapeLocked && pos.pixels) ? pos.pixels : sprite.pixels;
      const bmpInfo = bitmaps.get(JSON.stringify(currentPixels));
      
      source += `  { .x=${pos.x}, .y=${pos.y}, .w=${sprite.width}, .h=${sprite.height}, .bmp=${bmpInfo.name} }, // frame ${f}\n`;
    }
    source += `};\n\n`;
  });

  // 4. Final Animation Struct
  const layersVarName = `MOCHI_LAYERS_${name}`;
  source += `const MochiLayer ${layersVarName}[] = {\n`;
  sprites.forEach(sprite => {
    const layerVarName = `MOCHI_LAYER_${sanitizeName(sprite.name)}`;
    source += `  { .frame_count=${meta.totalFrames}, .delay_ms=${Math.round(1000/meta.fps)}, .frames=${layerVarName} },\n`;
  });
  source += `};\n\n`;

  source += `const MochiAnim MOCHI_ANIM_${name} = {\n  .layer_count = ${sprites.length},\n  .layers = ${layersVarName}\n};\n`;
  header += `extern const MochiAnim MOCHI_ANIM_${name};\n`;

  const readme = generateReadme(project);

  return { header, source, readme, memoryUsage: totalProgmem };
};
